name: Go

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Release Tags'
      body:
        description: 'Release Info'


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Golang info
      run: go env -w GO111MODULE=auto && go env
      
    - name: download
      run: go mod download
      
    - name: build
      run: |
       go build main.go -o TpScan_linux_amd64
       CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build main.go -o TpScan_Windows_amd64.exe
       CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build main.go -o TpScan_darwin_amd64
       
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.event.inputs.tags }}
        body: ${{ github.event.inputs.body }}
        files: |
          TpScan_Windows_amd64.exe
          TpScan_darwin_amd64
          TpScan_linux_amd64
