name: Go

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Golang info
      run: go env -w GO111MODULE=auto && go env
      
    - name: download
      run: go mod download
      
    - name: build
      run: |
       go build -o TpScan_linux_amd64 main.go
       CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o TpScan_Windows_amd64.exe main.go
       CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o TpScan_darwin_amd64 main.go
       
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          TpScan_Windows_amd64.exe
          TpScan_darwin_amd64
          TpScan_linux_amd64
